# Generated by Django 6.0 on 2026-01-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_created_on_resource_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_link',
            field=models.URLField(null=True),
        ),
    ]
