# Generated by Django 6.0 on 2026-01-01 21:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_resource_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
