# Generated by Django 6.0 on 2026-01-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.IntegerField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default=0),
        ),
    ]
