# Generated by Django 6.0 on 2026-01-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_rename_commentform_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
