# Generated by Django 6.0 on 2026-01-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_subject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
