# Generated by Django 6.0 on 2026-01-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_alter_resource_resource_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
