# Generated by Django 6.0 on 2026-01-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_alter_resource_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
