# Generated by Django 6.0 on 2026-01-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_comment_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
